### ISSUE TITLE
You cannot call a method on a null-valued expression.  Statement $ExcelSheet.Cells.Item($ExcelStartRow, $ExcelColNum) = $DateForExcel.ToString("yyyy-MM-dd HH:mm:ss")

### ISSUE THREAD

**Issue by bonfi** [VladDBA/PSBlitz#285] opened 2024-12-05 10:51 UTC
Hi, i have this problem when i write to excel the output:

`--------------------------------------------------------------------------------
       Starting in-depth database-specific check for xxxx.yyyy.aaaa.aa
--------------------------------------------------------------------------------
 Starting session activity collection process... √
 ->Active session data will be captured every 10 seconds.
 Retrieving instance information... √ - 17.02 seconds
 ->Writing instance info to Excel
 ->Writing resource info to Excel
 ->Writing Top 10 clients by connections to Excel
 ->Writing Session level options to Excel
 Retrieving TempDB usage data... √ - 0.44 seconds
 ->Writing TempDB space usage results to Excel
 ->Writing temp table results to Excel
 ->Writing sessions using TempDB results to Excel
 Retrieving open transaction info for DBDemo... √ - 0.19 seconds
 ->No open transactions found.
 Retrieving database info for DBDemo... √ - 15.63 seconds
 ->Writing Database Files Info results to Excel
 ->Writing Database Info results to Excel
 ->Writing Database Scoped Configuration results to Excel
 Retrieving instance health data... √ - 19.68 seconds
 ->Writing sp_Blitz results to Excel
 What's happening in a 30 seconds time-frame... √ - 30.38 seconds
 ->Writing sp_BlitzFirst results to Excel
 Retrieving waits recorded since instance startup... √ - 1.96 seconds
 ->Writing sp_BlitzFirst results to sheet Wait Stats
 ->Writing sp_BlitzFirst results to sheet Storage Stats
 ->Writing sp_BlitzFirst results to sheet Perfmon Stats
Get-Date: C:\Users\pa.li\Downloads\PSBlitz v4.5.0\PSBlitz\PSBlitz.ps1:3714
Line |
3714 |                              $DateForExcel = $DateTemp | Get-Date
     |                                                          ~~~~~~~~
     | The input object cannot be bound to any parameters for the command either because the command does not take
     | pipeline input or the input and its properties do not match any of the parameters that take pipeline input.

 Script execution was interrupted.
 ->Latest exception (if any):
 PS Error: Script Line 3715
 Message You cannot call a method on a null-valued expression.
 Statement $ExcelSheet.Cells.Item($ExcelStartRow, $ExcelColNum) = $DateForExcel.ToString("yyyy-MM-dd HH:mm:ss")
  Debug Column: FirstSampleTime
  Debug Value: 09/26/2024 05:29:54 +00:00
 Finishing up...
 Attempting to stop BlitzWho background process...
 ->Flag Table created
 ->Waiting for 20 seconds before getting job output.
 ->BlitzWho process no longer running √
 ->Successful runs: 10
 Attempting to retrieve session actvity data... √ - 0.73 seconds
 ->Exporting execution plans
 ->Writing sp_BlitzWho results to Excel
 ->Writing sp_BlitzWho aggregate results to Excel
 ->Writing Execution Log to Excel
--------------------------------------------------------------------------------
Execution completed in: 00:02:09
Generated files have been saved in:
 C:\Users\pa.li\Downloads\PSBlitz v4.5.0\PSBlitz\DBDemo_202412051130`
 
 Sql Version:
 _Microsoft SQL Server 2019 (RTM-CU23) (KB5030333) - 15.0.4335.1 (X64)   Sep 21 2023 17:28:44   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2022 Standard 10.0 <X64> (Build 20348: )_ 
 and i'm using: _PowerShell 7.4.6_
 
 i have: _Microsoft® Excel® for Microsoft 365 MSO (Version 2409 Build 16.0.18025.20214) 64-bit_
 
 
![image](https://github.com/user-attachments/assets/6aad48f2-c0ab-45d9-90f6-ae1c6eae6082)

**Comment by VladDBA** [comment] 2024-12-13 16:51
Hi @bonfi,

Thank you for providing the debug info. Can you also specify what collation your instance is using?

Thank you,

Vlad

**Comment by bonfi** [comment] 2024-12-16 08:45
Hi @VladDBA, 

my server collation is: Latin1_General_CI_AS

Thank you

**Comment by VladDBA** [comment] 2024-12-19 19:43
Hi @bonfi,

I've been able to reproduce this (not in the exact same place, but I it seems that it's just a matter of timing) in the following ways:
### Scenario 1
1. Open Excel (it doesn't even need to have a file opened, just the application itself).
2. Run SPBlitz
3. Close Excel while PSBlitz is still in the middle of the current execution
4. You'll get an error as soon as PSBlitz tires to write something to Excel again.

### Scenario 2
1. Run SPBlitz
2. Open Excel.
3. Close Excel while PSBlitz is still in the middle of the current execution
4. You'll get an error as soon as PSBlitz tires to write something to Excel again.

The error is caused by the same thing: when you close Excel you also close it for PSBlitz so any handle it had related to Excel is now null. This leads to the same message:
` Message You cannot call a method on a null-valued expression.`
With just the specifics such switching sheets, writing to a cell, saving the .xlsx file, varying depending on what PSBlitz does next right after Excel was closed.

So, my question is now, in case you can recall the exact situation:
Any chance either of the two scenarios might apply to your case?
Would you mind retrying without having Excel opened at the same time with PSBlitz running?

If you can confirm that this is the case, I'll add a note about this in the documentation.

**Comment by bonfi** [comment] 2024-12-20 17:57
Hi @VladDBA, 

I confirm that the error comes up for me with excel closed

![image](https://github.com/user-attachments/assets/cc4ac38c-c04e-42b4-b468-9049ff2b1cdd)
(I don't know why but now the error comes out in Italian language :) )

**Comment by VladDBA** [comment] 2024-12-20 18:53
Thank you for checking, @bonfi!
2 other things I could think of would be:
1. The PSBlitz/output folder is in a folder that gets synced through OneDrive. So, OneDrive's syncing may interfere with the Excel file that PSBlitz is writing to. 
I know I've had issues with this in the past, and I did add a workaround for that, but I always try to avoid OneDrive synced folders for PSBlitz's output, just in case.
2. The OS system language and, by extension, the culture of the PS session is different enough to mess with datetime formatting. I tend to think this is highly unlikely since the culture can't change the datetime value so much that ToString won't be able to convert it and throw a null exception.

Do you get any errors when using the HTML output?

Either way, I'll try and test for both.

**Closed** 2024-12-27 17:09 UTC
Labels: bug

**Comment by VladDBA** [comment] 2024-12-29 23:22
Hi @bonfi,
Forgot to add an update here with the latest release.
If it's not related to OneDrive or Excel closing then the issue should (hopefully) be fixed in v5.0.0 since I've moved all the date time conversions out of PS. 
Plus, if one sheet fails to populate (for whatever reason), PSBlitz shouldn't exit the execution, but move forward with the next check instead.
For the next release I'm also planning on building some retry logic in case Excel crashes or the .xlsx file closes for some reason.

Have a happy new year!
